NAME = record_18

FILES_DSP = Record18Plugin.cpp


#DEBUG=true
include ../../DPF/Makefile.plugins.mk


#TARGETS += ladspa
#TARGETS += lv2_sep
#TARGETS += vst2
#TARGETS += vst3
#TARGETS += clap
TARGETS += jack

all: $(TARGETS)
